# Generated by Django 2.1.3 on 2018-11-28 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Educacion_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Area_Educacion_Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Area_Educativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia_Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=60)),
                ('tipo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Edad_Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad_minima', models.SmallIntegerField()),
                ('edad_maxima', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Educacion_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('institucion', models.CharField(max_length=40)),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Educacion_Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=256)),
                ('contacto', models.CharField(max_length=40)),
                ('informacion', models.TextField(max_length=640)),
                ('sitio_web', models.CharField(max_length=40)),
                ('verificado', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Civil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=40)),
                ('empresa', models.CharField(max_length=40)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Frecuencia_Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes_entrada', models.TimeField()),
                ('lunes_salida', models.TimeField()),
                ('martes_entrada', models.TimeField()),
                ('martes_salida', models.TimeField()),
                ('miercoles_entrada', models.TimeField()),
                ('miercoles_salida', models.TimeField()),
                ('jueves_entrada', models.TimeField()),
                ('jueves_salida', models.TimeField()),
                ('viernes_entrada', models.TimeField()),
                ('viernes_salida', models.TimeField()),
                ('sabado_entrada', models.TimeField()),
                ('sabado_salida', models.TimeField()),
                ('domingo_entrada', models.TimeField()),
                ('domingo_salida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcion_Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad_Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=60)),
                ('tipo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma_Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Idioma')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Idioma_Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Idioma_Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.BooleanField()),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Idioma')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Idioma_Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_Educativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Prestacion_Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestacion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Remuneracion_Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('maximo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('frecuencia', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tamaño_Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=80)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=256)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_de_nacimiento', models.DateField()),
                ('es_hombre', models.BooleanField()),
                ('experiencia', models.SmallIntegerField()),
                ('quien_soy', models.TextField(max_length=640)),
                ('informacion_adicional', models.TextField(max_length=640)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Estado_Civil')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=40)),
                ('descripcion', models.TextField(max_length=400)),
                ('sexo', models.BooleanField()),
                ('experiencia_minima', models.SmallIntegerField()),
                ('informacion_adicional', models.TextField(max_length=640)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_limite', models.DateTimeField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Departamento')),
                ('edad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Edad_Vacante')),
                ('frecuencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Frecuencia_Vacante')),
                ('remuneracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Remuneracion_Vacante')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tipo')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ubicacion')),
            ],
        ),
        migrations.AddField(
            model_name='prestacion_vacante',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vacante'),
        ),
        migrations.AddField(
            model_name='idioma_vacante',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vacante'),
        ),
        migrations.AddField(
            model_name='idioma_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
        ),
        migrations.AddField(
            model_name='habilidad_vacante',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vacante'),
        ),
        migrations.AddField(
            model_name='habilidad_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
        ),
        migrations.AddField(
            model_name='funcion_vacante',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vacante'),
        ),
        migrations.AddField(
            model_name='experiencia_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tamaño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tamaño_Empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ubicacion'),
        ),
        migrations.AddField(
            model_name='educacion_vacante',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Nivel_Educativo'),
        ),
        migrations.AddField(
            model_name='educacion_vacante',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vacante'),
        ),
        migrations.AddField(
            model_name='educacion_usuario',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Nivel_Educativo'),
        ),
        migrations.AddField(
            model_name='educacion_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
        ),
        migrations.AddField(
            model_name='competencia_vacante',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vacante'),
        ),
        migrations.AddField(
            model_name='competencia_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
        ),
        migrations.AddField(
            model_name='area_educacion_vacante',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Area_Educativa'),
        ),
        migrations.AddField(
            model_name='area_educacion_vacante',
            name='educacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Educacion_Vacante'),
        ),
        migrations.AddField(
            model_name='area_educacion_usuario',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Area_Educativa'),
        ),
        migrations.AddField(
            model_name='area_educacion_usuario',
            name='educacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Educacion_Usuario'),
        ),
    ]
