# Generated by Django 2.1.3 on 2018-11-28 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181127_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frecuencia_Remuneracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='remuneracion_vacante',
            name='frecuencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Frecuencia_Remuneracion'),
        ),
    ]
