# Generated by Django 2.1.3 on 2018-11-29 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181128_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracter', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='competencia_vacante',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='educacion_vacante',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='habilidad_vacante',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='idioma_vacante',
            name='tipo',
        ),
        migrations.AddField(
            model_name='competencia_vacante',
            name='caracter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Caracter'),
        ),
        migrations.AddField(
            model_name='educacion_vacante',
            name='caracter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Caracter'),
        ),
        migrations.AddField(
            model_name='habilidad_vacante',
            name='caracter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Caracter'),
        ),
        migrations.AddField(
            model_name='idioma_vacante',
            name='caracter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Caracter'),
        ),
    ]
