# Generated by Django 2.1.3 on 2018-11-29 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181128_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area_educacion_usuario',
            name='area',
        ),
        migrations.RemoveField(
            model_name='area_educacion_usuario',
            name='educacion',
        ),
        migrations.RemoveField(
            model_name='area_educacion_vacante',
            name='area',
        ),
        migrations.RemoveField(
            model_name='area_educacion_vacante',
            name='educacion',
        ),
        migrations.AddField(
            model_name='educacion_usuario',
            name='area',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Area_Educativa'),
        ),
        migrations.AddField(
            model_name='educacion_vacante',
            name='area',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Area_Educativa'),
        ),
        migrations.DeleteModel(
            name='Area_Educacion_Usuario',
        ),
        migrations.DeleteModel(
            name='Area_Educacion_Vacante',
        ),
    ]
