# Generated by Django 2.1.3 on 2018-11-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181128_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edad_vacante',
            name='edad_maxima',
        ),
        migrations.RemoveField(
            model_name='edad_vacante',
            name='edad_minima',
        ),
        migrations.AddField(
            model_name='edad_vacante',
            name='edad',
            field=models.CharField(default='', max_length=20),
        ),
    ]
