# Generated by Django 2.1.3 on 2018-11-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181128_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia_vacante',
            name='domingo_entrada',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='frecuencia_vacante',
            name='domingo_salida',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='frecuencia_vacante',
            name='jueves_entrada',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='frecuencia_vacante',
            name='jueves_salida',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='frecuencia_vacante',
            name='lunes_entrada',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='frecuencia_vacante',
            name='lunes_salida',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='frecuencia_vacante',
            name='martes_entrada',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='frecuencia_vacante',
            name='martes_salida',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='frecuencia_vacante',
            name='miercoles_entrada',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='frecuencia_vacante',
            name='miercoles_salida',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='frecuencia_vacante',
            name='sabado_entrada',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='frecuencia_vacante',
            name='sabado_salida',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='frecuencia_vacante',
            name='viernes_entrada',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='frecuencia_vacante',
            name='viernes_salida',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
