# Generated by Django 2.1.3 on 2018-12-02 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Educativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia_Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Edad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minima', models.SmallIntegerField()),
                ('maxima', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Educacion_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('institucion', models.CharField(max_length=64)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Area_Educativa')),
            ],
        ),
        migrations.CreateModel(
            name='Educacion_Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Area_Educativa')),
            ],
        ),
        migrations.CreateModel(
            name='Frecuencia_Remuneracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad_Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_Educativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.DecimalField(decimal_places=2, max_digits=3)),
                ('competencia', models.DecimalField(decimal_places=2, max_digits=3)),
                ('idioma', models.DecimalField(decimal_places=2, max_digits=3)),
                ('educacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('experiencia', models.BooleanField()),
                ('sexo', models.BooleanField()),
                ('edad', models.BooleanField()),
                ('tipo', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Remuneracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minima', models.DecimalField(decimal_places=2, max_digits=22)),
                ('maxima', models.DecimalField(decimal_places=2, max_digits=22)),
                ('frecuencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Frecuencia_Remuneracion')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=256)),
                ('nombre', models.CharField(max_length=50)),
                ('quien_soy', models.TextField(max_length=640)),
                ('fecha_de_nacimiento', models.DateField()),
                ('años_de_experiencia', models.SmallIntegerField()),
                ('informacion_adicional', models.TextField(max_length=640)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=40)),
                ('descripcion', models.TextField(max_length=400)),
                ('frecuencia', models.CharField(max_length=80)),
                ('años_de_experiencia_minima', models.SmallIntegerField()),
                ('informacion_adicional', models.TextField(max_length=640)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Departamento')),
                ('edad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Edad')),
                ('remuneracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Remuneracion')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sexo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tipo_Vacante')),
            ],
        ),
        migrations.AddField(
            model_name='postulacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vacante'),
        ),
        migrations.AddField(
            model_name='habilidad_vacante',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vacante'),
        ),
        migrations.AddField(
            model_name='habilidad_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
        ),
        migrations.AddField(
            model_name='educacion_vacante',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Nivel_Educativo'),
        ),
        migrations.AddField(
            model_name='educacion_vacante',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vacante'),
        ),
        migrations.AddField(
            model_name='educacion_usuario',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Nivel_Educativo'),
        ),
        migrations.AddField(
            model_name='educacion_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
        ),
        migrations.AddField(
            model_name='competencia_vacante',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vacante'),
        ),
        migrations.AddField(
            model_name='competencia_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
        ),
    ]
