# Generated by Django 2.1.3 on 2018-12-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_educativa',
            name='area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nivel_educativo',
            name='nivel',
            field=models.CharField(max_length=50),
        ),
    ]
