# Generated by Django 2.1.3 on 2018-12-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181202_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='publicada',
        ),
        migrations.AddField(
            model_name='vacante',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
