# Generated by Django 2.1.3 on 2018-12-03 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181202_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacante',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='vacante',
            name='remuneracion',
        ),
        migrations.AddField(
            model_name='edad',
            name='vacante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Vacante'),
        ),
        migrations.AddField(
            model_name='remuneracion',
            name='vacante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Vacante'),
        ),
    ]
