# Generated by Django 2.1.3 on 2018-12-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181202_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sexo',
            name='sexo',
            field=models.CharField(max_length=15),
        ),
    ]
