# Generated by Django 2.1.3 on 2018-12-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181203_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='postulacion',
            name='categoria',
            field=models.CharField(default='', max_length=20),
        ),
    ]
